  Implementing ***Linear Regression*** model


**1.Importing the required libraries**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn


**2.Load the data**


In [3]:
data=pd.read_csv('Advertising.csv')

In [4]:
data.head()


Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [5]:
data.corr()['Sales']

Unnamed: 0   -0.051616
TV            0.782224
Radio         0.576223
Newspaper     0.228299
Sales         1.000000
Name: Sales, dtype: float64

**3.Setting the training features and predicting feature**


In [6]:
X=data[['TV','Radio','Newspaper']].to_numpy()
X.shape

(200, 3)

In [7]:
Y=data['Sales'].to_numpy()
Y.shape

(200,)

In [8]:
X


array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4],
       [  8.7,  48.9,  75. ],
       [ 57.5,  32.8,  23.5],
       [120.2,  19.6,  11.6],
       [  8.6,   2.1,   1. ],
       [199.8,   2.6,  21.2],
       [ 66.1,   5.8,  24.2],
       [214.7,  24. ,   4. ],
       [ 23.8,  35.1,  65.9],
       [ 97.5,   7.6,   7.2],
       [204.1,  32.9,  46. ],
       [195.4,  47.7,  52.9],
       [ 67.8,  36.6, 114. ],
       [281.4,  39.6,  55.8],
       [ 69.2,  20.5,  18.3],
       [147.3,  23.9,  19.1],
       [218.4,  27.7,  53.4],
       [237.4,   5.1,  23.5],
       [ 13.2,  15.9,  49.6],
       [228.3,  16.9,  26.2],
       [ 62.3,  12.6,  18.3],
       [262.9,   3.5,  19.5],
       [142.9,  29.3,  12.6],
       [240.1,  16.7,  22.9],
       [248.8,  27.1,  22.9],
       [ 70.6,  16. ,  40.8],
       [292.9,  28.3,  43.2],
       [112.9,  17.4,  38.6],
       [ 97.2,   1.5,  30. ],
       [26

**4.Importing the required model and training the model with the data**


In [9]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X,Y)
pred=model.predict(X)
pred.shape

(200,)

In [10]:
pred

array([20.52397441, 12.33785482, 12.30767078, 17.59782951, 13.18867186,
       12.47834763, 11.72975995, 12.12295317,  3.72734086, 12.55084872,
        7.0322992 , 17.28512918, 10.57712073,  8.82630048, 18.43436638,
       20.81929952, 12.82365674, 23.22495716,  9.95168206, 14.16607293,
       18.10076728, 14.7405382 ,  6.4891503 , 16.5459329 ,  8.14651887,
       15.6100386 , 14.98951429, 17.05167344, 19.41053803,  9.14402389,
       21.6339338 , 11.3460929 ,  7.63888314, 18.86426829,  7.57483051,
       17.00682618, 23.40590052, 15.62347779,  9.90868103, 20.44761039,
       16.37766467, 17.2959832 , 21.59580326, 13.96385684,  8.88787996,
       15.16152314,  8.87338673, 21.7226299 , 16.26362018,  8.1681656 ,
       12.63121132,  9.33981296, 20.66297563, 19.94469957, 20.37443008,
       21.2926106 ,  8.52771254, 12.77458802, 21.89805198, 18.13348698,
        5.74215558, 22.89067208, 16.78426073, 13.21069202, 16.97773556,
        7.84904532,  9.01603163, 12.0370073 , 18.97657924, 21.10

**5.Calculating the error percentage**

In [11]:
from sklearn.metrics import mean_absolute_percentage_error,accuracy_score,mean_squared_error
mean_absolute_percentage_error(Y,pred)

0.13877847090457157

In [12]:
mean_squared_error(Y,pred)


2.784126314510936

**6.Model is trained and ready to predict the required values**

In [13]:
model.predict([[230.1,  37.8,  69.2]]), Y[0]

(array([20.52397441]), 22.1)

In [14]:
X[0]

array([230.1,  37.8,  69.2])